import Head from "next/head";
import Header from "../components/Header";
import Results from "../components/Results";
import { defaults } from "./_app";

export default function Actors( {results} ) {
  return (
    <div>
      <Head>
        <title>Actors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Results results={results} type={"actors"}/>
    </div>
  );
}

export async function getServerSideProps(context) {
  const baseUrl = `${defaults.app.apiUrl}/actors`
  const queryString = context.query.searchTerm ? `?searchTerm=${context.query.searchTerm}`: ''

  const request = await fetch(
    baseUrl + queryString
  ).then((res) => res.json());

  return {
    props: {
      results: request.actors?? [],
    },
  };
}
